### ISSUE TITLE
Adding spacing bewteen lines

### ISSUE THREAD

**Issue by jreezy11** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#10]
We normally like to add more spacing after sentences than we're currently getting. For example, we rarely put 3 sentences together without skipping a line.

**Comment by angelbt91** [comment]
Hello! Based on your message, I think this is not the repo where you wanted to report the issue, as there's nothing related to what you mention in the message.

Then, I'm going to close this issue and the other one you opened as well, but if I'm wrong and you wanted to report something for this repo, don't hesitate to open another issue with more details :)

Thanks!
