### ISSUE TITLE
Client IP Addresses Affecting Attribution and Optimization

### ISSUE THREAD

**Issue by fikiismyname** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#15]
### Issue Description
Our server is sending one or more client IP addresses for Lead events that are associated with multiple users. This situation may affect the attribution and optimization of our ad campaigns.

### Expected Behavior
The expected behavior is to resolve the issue related to client IP addresses affecting the attribution and optimization of ad campaigns.

### Current Behavior
Currently, we are experiencing issues with client IP addresses being associated with multiple users, which has a negative impact on our ad campaigns.

### Additional Context
This issue is critical as it directly impacts the accuracy of attribution and optimization in our ad campaigns. It requires immediate attention to ensure data integrity and campaign effectiveness.

### Priority
High

### Labels
- bug
- data quality

**Comment by mjadsmurai** [comment]
```
Currently, we are experiencing issues with client IP addresses being associated with multiple users, which has a negative impact on our ad campaigns.
```
As part of the other issue, this is something you won't be able to fully avoid. A university for example will probably have a single IP v4 and use it for all students by using CG-NAT ( https://en.wikipedia.org/wiki/Carrier-grade_NAT ) and other techniques.
The only way this could be avoided is if the entire world used v6, which is not going to happen any time soon i'm afraid.
