### ISSUE TITLE
Is this template compatible with HTML/JS site?

### ISSUE THREAD

**Issue by usamasindhu** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#16]
Is this template compatible with HTML/JS site. I see the code base and looks like smarty is compatible with PHP which is supposed to work with WordPress. I'm kind of new to web development and ads management and trying to integrate the conversion API in a pure HTML/CSS website.

**Comment by mjadsmurai** [comment]
Hi! 
This template is the source code of the tag, you're not expected to apply it directly on the website :)
All you have to do is to add Google Tag Manager to your website and then add this tag from the GTM gallery:
https://tagmanager.google.com/gallery/#/owners/Adsmurai-Google-Tag-Manager-Templates/templates/adsmurai-facebook-pixel-and-conversions-api
