### ISSUE TITLE
How to add more parameters?

### ISSUE THREAD

**Issue by Contributolo** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#17]
Hi there,

thank you for the nice template :)!

I have a newb question. How can I send more parameters for lead (form submission) and page view? I don't get it :-/.

For example page view is sending:
- IP address
- User agent
- Browser-ID

But I would like to send these parameters:
- fbc
- FB Login-ID
- External ID
- Mail address
- name

Do you have a documentation for this?

Would be awesome.

Big thank you in advance!

**Comment by mjadsmurai** [comment]
Those params are available under the different sections that you can see on this tag :)
 Ex, email, name and external id can be found on `Customer information parameters` section:
![Screenshot from 2024-02-19 08-07-51](https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api/assets/142219663/08d92e0a-1d26-4d62-94a0-7f082852c6c8)
