### ISSUE TITLE
GA4 Events?

### ISSUE THREAD

**Issue by mdgibbons** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#21]
I've installed this tag to work with the [AdSmurai FB Conversions API Client](https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-conversions-api-client) and it's working fine for Facebook events.  Events are showing as coming from both browser and server (using Stape.io) and correctly deduplicating.  All good.

I also see there are spots for lots of other pixels (TikTok, Pinterest, Google Analytics 4, etc..etc...).  But when I added my Google Analytics 4 Measurement Id to my specific GTM Tag (ViewContent Event triggered on a specific page view), events never shows up in GA4.   I'm sure I'm missing something - any suggestions?

**Comment by mjadsmurai** [comment]
Hi!
This tag is designed to work with OneTag https://www.adsmurai.com/en/product/serverless-tracking .
The template that you're using is server side for GTM and only has support for Meta. All other platforms don't work with the selfhosted version.

**Comment by mdgibbons** [comment]
Thanks for the clarification!
