### ISSUE TITLE
disablePushState

### ISSUE THREAD

**Issue by DigitalConnexia** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#4]
Hi,
it would be a good improvement for your tag template to have an option to disable default tracking for PushState on PWA/SPA applications

fbq.disablePushState = true

cfr:
https://developers.facebook.com/docs/meta-pixel/implementation/tag_spa
(Note: You can set disablePushState to true to stop sending PageView events on history state changes but it is not recommended)

**Comment by angelbt91** [comment]
Hi!

Thanks for opening this issue :)

I was unaware of this feature, thanks for notifying me about it. I will check the docs to understand more about it and I'll probably add it in the next version of the template, which should be coming soon.

Whenever the next version with that feature is released, I will make sure to notify that in this issue.

Thanks!

**Comment by DigitalConnexia** [comment]
Thanks. In our opinion it is important because the mere fact of having the FB client library sends those hits to FB and they do not pair with server side ones. (this hits do not appear also in GTM, you can see them only via network requests)

**Comment by angelblancoadsmurai** [comment]
I just released this template's version 1.0, which adds support for "disablePushState" under the "Pixel setup" tab :) In the next hours GTM should notify you about a new version of this tag.

If you find any bug, feel free to open another issue.

Thanks again for opening this one to let me know about this feature! :)
