### ISSUE TITLE
Adding context to the 7 day welcome flow

### ISSUE THREAD

**Issue by jreezy11** [Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api#9]
For the welcome flow (7 day), it often talks as if the reader already has their product, which they don't, so maybe we can add a sentence to the prompt to give the copywriter more context

**Comment by angelbt91** [comment]
Closing, see https://github.com/Adsmurai-Google-Tag-Manager-Templates/adsmurai-facebook-pixel-and-conversions-api/issues/10#issuecomment-1681648293
